Fix Platinum Blissey_22
axpendix/tcgone-engine-contrib pull request #1254
Opened 2021-05-27 22:32 UTC by luongthomas

Fix crash on Nurse call ability

2021-05-27 22:45 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [BLISSEY_22](https://trello.com/c/Vcy6BlhT/992-blissey22)

2021-05-27 23:03 UTC, starg09 commented on src/tcgwars/logic/impl/gen4/Platinum.groovy
> +              assert my.all.find {it.numberOfDamageCounters} : "Your Pokémon are healthy"
> Q. Can I use Blissey's "Nurse Call" Poke-POWER to discard a card from my hand even if I have no damaged Pokemon in play?
>
> A. Yes, you can. (Jun 11, 2009 PUI Rules Team)

This shouldn't be asserted at all (heal below could be replaced with a filer, then doing the heal only if valid targets are found.

2021-05-27 23:03 UTC, starg09 requested changes

2021-05-27 23:03 UTC, starg09 commented on src/tcgwars/logic/impl/gen4/Platinum.groovy
> +              assert my.all.find {it.numberOfDamageCounters} : "Your Pokémon are healthy"
> Q. Can I use Blissey's "Nurse Call" Poke-POWER to discard a card from my hand even if I have no damaged Pokemon in play?
>
> A. Yes, you can. (Jun 11, 2009 PUI Rules Team)

This shouldn't be asserted at all (heal below could be replaced with a filer, then doing the heal only if valid targets are found.

2021-05-29 04:31 UTC, starg09 commented on src/tcgwars/logic/impl/gen4/Platinum.groovy
> +              assert my.all.find {it.numberOfDamageCounters} : "Your Pokémon are healthy"
Not going to lie, I've no clue what I meant to say when I wrote "could be replaced with a filer" 😓 

But with no assert, there's a need for one more change, suggesting it in a second.

2021-05-29 04:35 UTC, starg09 commented on src/tcgwars/logic/impl/gen4/Platinum.groovy
> +              heal 20, my.all.findAll{it.numberOfDamageCounters}.select("Heal which Pokémon"), Source.POKEPOWER
```suggestion
              if (my.all.any{it.numberOfDamageCounters}) 
                heal 20, my.all.findAll{it.numberOfDamageCounters}.select("Heal which Pokémon"), Source.POKEPOWER
```

2021-05-29 04:36 UTC, starg09 commented on src/tcgwars/logic/impl/gen4/Platinum.groovy
> +              heal 20, my.all.findAll{it.numberOfDamageCounters}.select("Heal which Pokémon"), Source.POKEPOWER
Just to avoid a popup when that part can't be done.

2021-05-29 04:44 UTC, starg09 approved these changes

2021-07-15 23:25 UTC, merged