Legends Awakened Bugfixes
axpendix/tcgone-engine-contrib pull request #1268
Opened 2021-06-08 17:56 UTC by luongthomas

Addressing issues regarding the Gen4 Legends Awakened set bugs found on trello

2021-06-08 17:57 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [KYOGRE_32](https://trello.com/c/DVNVyDZl/1137-kyogre32)

2021-06-08 17:57 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [LOPUNNY_33](https://trello.com/c/wNvYrkbP/1138-lopunny33)

2021-06-08 18:07 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [REGICE_36](https://trello.com/c/u8FFtzlh/1141-regice36)

2021-06-08 18:08 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [REGISTEEL_39](https://trello.com/c/pQq7ZTa1/1144-registeel39)

2021-06-08 18:14 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [SHEDINJA_40](https://trello.com/c/gg8oY9Rp/1145-shedinja40)

2021-06-08 18:26 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [VICTREEBEL_44](https://trello.com/c/d9lZJ2L1/1149-victreebel44)

2021-06-08 18:30 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [VILEPLUME_45](https://trello.com/c/BhEyJL31/1150-vileplume45)

2021-06-08 18:32 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [ANORITH_46](https://trello.com/c/YAYqKSja/1151-anorith46)

2021-06-08 18:46 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [EXEGGUTOR_54](https://trello.com/c/58GPwWjY/1159-exeggutor54)

2021-06-08 18:52 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [HOUNDOOM_57](https://trello.com/c/pdzeD6uL/1162-houndoom57)

2021-06-08 19:24 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [LEDIAN_60](https://trello.com/c/9svAtGV2/1165-ledian60)

2021-06-08 19:25 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [LUCARIO_61](https://trello.com/c/TdTE8fgP/1166-lucario61)

2021-06-08 19:29 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [NINJASK_67](https://trello.com/c/9hwCPqcw/1172-ninjask67)

2021-06-08 19:34 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [TAUROS_74](https://trello.com/c/KDCQsXNO/1179-tauros74)

2021-06-08 19:48 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [TENTACRUEL_75](https://trello.com/c/kIXtUHuH/1180-tentacruel75)

2021-06-08 19:49 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [UNOWN_J_76](https://trello.com/c/TYhys635/1181-unownj76)

2021-06-08 20:15 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [UNOWN_R_77](https://trello.com/c/X8osSlWW/1182-unownr77)

2021-06-08 20:17 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [UNOWN_U_78](https://trello.com/c/AqwTVvh7/1183-unownu78)

2021-06-08 20:33 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [BELDUM_83](https://trello.com/c/j8B2XXap/1188-beldum83)

2021-06-08 20:39 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [BELLSPROUT_85](https://trello.com/c/n6AayR6O/1190-bellsprout85)

2021-06-08 20:45 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [SNEASEL_120](https://trello.com/c/zWOExvAe/1225-sneasel120)

2021-06-08 20:46 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [CHINCHOU_87](https://trello.com/c/dAGzyuMC/1192-chinchou87)

2021-06-08 20:51 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [POKE_RADAR_133](https://trello.com/c/c32RiKAU/1238-pokeradar133)

2021-06-08 21:05 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [MEWTWO_LV_X_144](https://trello.com/c/xTBaPeje/1249-mewtwolvx144)

2021-06-08 21:21 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [MESPRIT_LV_X_143](https://trello.com/c/IIDcmX45/1248-mespritlvx143)

2021-06-08 21:40 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [UNOWN_Y_81](https://trello.com/c/jXBkahU1/1186-unowny81)

2021-06-09 07:20 UTC, luongthomas commented
![](https://github.trello.services/images/mini-trello-icon.png) [POLIWRATH_35](https://trello.com/c/N4ZkvfQT/1140-poliwrath35)

2021-06-09 23:08 UTC, starg09 reviewed
Looks good, left some comments :)

2021-06-09 23:08 UTC, starg09 commented on src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
> -                if (self.owner.opposite.pbg.active.evolution && bg.currentTurn==self.owner.opposite && ef.effectType != DAMAGE){
Not necessarily specific to this card: How does this work with Lv.X basics? Also, basics with a card on top (not relevant to worlds formats, but there's Ditto BCR which could cause issues in unlimited/HoF)

2021-06-09 23:08 UTC, starg09 commented on src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
>                    }
Same issue as the other comment on the card, but also adding an "opponent's pokemon" check:

```suggestion
                if (ef.attacker.owner != self.owner && ef.attacker.evolution) {
                  bg.dm().each {
                    if (it.to == self && it.dmg.value && it.notNoEffect) {
                      it.dmg = hp(0)
                      bc "Psybarrier prevents damage"
                    }
                  }
```

2021-06-09 23:18 UTC, flagrama requested changes

2021-06-09 23:18 UTC, flagrama commented on src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
> +              while(opp.hand.size() > 5) {
Clearer to include the number used in the card text in the code.

```suggestion
              while(opp.hand.size() >= 6) {
```

2021-06-09 23:18 UTC, flagrama commented on src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
> +                def toDiscard = my.hand.filterByBasicEnergyType(W).select(min: 0, max: 2, "For each [W] Energy discarded, do +10")
It does not state "Basic Energy cards." Theoretically if a Special Energy card is released that provides [W] by default, this attack should be able to discard it.

2021-06-09 23:18 UTC, flagrama commented on src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
> +                def energies = opp.discard.filterByType(ENERGY).select(min:0, max: 2, "Select up to 2 Energy Cards to attach")
Up to means 1 or more. Not 0. May is the keyword used for 0 or more.

2021-06-09 23:18 UTC, flagrama commented on src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
>                    assert deck.notEmpty : "Deck is empty"
These should be in the if statement. No reason to ask the player "want to use this ability?" "too bad you can't"

2021-06-09 23:18 UTC, flagrama commented on src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
> +              } : "Uxie Lv.X and Azelf Lv.X are not in play"
`findAll` isn't necessary, `find` or `any` should be enough.

2021-06-11 21:15 UTC, luongthomas commented on src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
> +                      discardSelfEnergy C
I'm actually not sure how to solve this one and I will move the associated trello card to backlog

2021-06-11 21:18 UTC, luongthomas commented on src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
>                }
I've changed it to only look for TRAINERs

2021-06-11 21:21 UTC, merged