Chilling Reign Implementation Pt 2
axpendix/tcgone-engine-contrib pull request #1279
Opened 2021-06-17 19:55 UTC by luongthomas

2021-06-18 03:16 UTC, starg09 commented on src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> +                new Knockout(defending).run(bg)
This needs to be enclosed as a targeted effect I think? Otherwise stuff like "Unaware" won't prevent it iirc.

2021-06-18 07:06 UTC, starg09 requested changes
Several of these are just comments, no need to implement them.

2021-06-18 07:06 UTC, starg09 commented on src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> +              if (self.cards.energyCount()) {
```suggestion
              if (self.cards.hasType(BASIC_ENERGY) {
```

2021-06-18 07:06 UTC, starg09 commented on src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> +                discardStadium()
```suggestion
                afterDamage {
                  discardStadium()
                }
```

2021-06-18 19:17 UTC, luongthomas commented on src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> +              if (self.energyCards.size() == defending.energyCards.size()) {
self.getEnergyCount()?

Shows an error if I do `self.energyCards.energyCount()`

2021-06-18 19:19 UTC, luongthomas commented on src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> +              if (bg.turnCount == 2) maxSearch = 3
Thanks looks good!

2021-06-18 19:21 UTC, luongthomas commented on src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> +              def energiesToDiscard = self.cards.select(min:0, max:self.cards.filterByType(ENERGY).size())
Nice catch!  What a useful static method

2021-06-18 19:27 UTC, merged

2021-06-18 19:44 UTC, starg09 commented on src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> +              if (self.energyCards.size() == defending.energyCards.size()) {
Yeah, my bad was a bit late already 😅 

Should be good like that

2021-06-18 19:47 UTC, starg09 commented on src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> +              }
Any reason this wasn't commited as a fix?

2021-06-18 20:10 UTC, luongthomas commented on src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> +              }
I didn't see the collapsed comments :(

2021-06-18 21:34 UTC, luongthomas commented on src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> +              shuffleDeck()
What would the `if` condition be?

2021-06-18 21:40 UTC, starg09 commented on src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> +              shuffleDeck()
only run everything if there's free space in bench.

2021-06-26 01:38 UTC, luongthomas commented on src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> +              }
Looks like it works on my end