pokemofd foisl 8
axpendix/tcgone-engine-contrib pull request #954
Opened 2020-09-18 05:44 UTC by TheAquaPiplup

bad

2020-09-18 18:01 UTC, flagrama requested changes
I've only reviewed the rares so far. You also don't need `PokemodFossil.` in front of the enum value in any of the copies you are doing since they are in that same file.

You also need to replace the imports at the top with this:
```
package tcgwars.logic.impl.pokemod

import tcgwars.logic.impl.gen1.Fossil

import static tcgwars.logic.card.HP.*;
import static tcgwars.logic.card.Type.*;
import static tcgwars.logic.card.CardType.*;
import static tcgwars.logic.groovy.TcgBuilders.*;
import static tcgwars.logic.groovy.TcgStatics.*
import static tcgwars.logic.effect.ability.Ability.ActivationReason.*
import static tcgwars.logic.effect.EffectType.*;
import static tcgwars.logic.effect.Source.*;
import static tcgwars.logic.effect.EffectPriority.*
import static tcgwars.logic.effect.special.SpecialConditionType.*
import static tcgwars.logic.card.Resistance.ResistanceType.*

import java.util.*;
import org.apache.commons.lang.WordUtils;
import tcgwars.entity.*;
import tcgwars.logic.*;
import tcgwars.logic.card.*;
import tcgwars.logic.card.energy.*;
import tcgwars.logic.card.pokemon.*;
import tcgwars.logic.card.trainer.*;
import tcgwars.logic.effect.*;
import tcgwars.logic.effect.ability.*;
import tcgwars.logic.effect.advanced.*;
import tcgwars.logic.effect.basic.*;
import tcgwars.logic.effect.blocking.*;
import tcgwars.logic.effect.event.*;
import tcgwars.logic.effect.getter.*;
import tcgwars.logic.effect.special.*;
import tcgwars.logic.util.*;

/**
 * @author axpendix@hotmail.com
 */
```
Otherwise this will just cause a bunch of errors.

2020-09-18 18:47 UTC, starg09 commented on src/tcgwars/logic/impl/pokemod/PokemodFossil.groovy
> +              tar.damage+=hp(10)
Yeah, though I'd still manually reduce the src.damage value, using directDamage for tar.

> Effects that prevent you from healing or from removing damage counters do not affect moving those damage counters between Pokémon. (Dec 1, 2011 TPCi Rules Team)

2020-09-18 18:52 UTC, starg09 commented on src/tcgwars/logic/impl/pokemod/PokemodFossil.groovy
> +                }
Wording is changed in Pokemod's version it seems, but Pluspower still only affects the Defending Pokémon apparently.

The sum of tails for a final self damage sounds good, less spam in the log 👍 

Would maybe add a string at the start of Flip, as to differentiate for Which Pokémon the flip is for.

2020-09-18 19:46 UTC, flagrama commented on src/tcgwars/logic/impl/pokemod/PokemodFossil.groovy
> +                }
Would it spam? Most of the time Damage gets added together, then applied after the closure, doesn't it?

2020-09-19 05:01 UTC, flagrama commented on src/tcgwars/logic/impl/pokemod/PokemodFossil.groovy
> +              def src =chocies.select()
You're gonna have to double check your spelling here.

2020-09-21 00:27 UTC, starg09 commented on src/tcgwars/logic/impl/pokemod/PokemodFossil.groovy
> +  ZAPDOS_EX_88 ("Zapdos", "87", Rarity.ULTRARARE, [BASIC, POKEMON, _LIGHTNING_]),
Remember to fix the collectionValue if changing the number in the enum :)

```suggestion
  PSYDUCK_78 ("Psyduck", "78", Rarity.RARE, [BASIC, POKEMON, _WATER_]),
  DRAGONITE_79 ("Dragonite", "79", Rarity.HOLORARE, [STAGE2, EVOLUTION, POKEMON, _COLORLESS_]),
  GENGAR_80 ("Gengar", "80", Rarity.HOLORARE, [STAGE2, EVOLUTION, POKEMON, _PSYCHIC_]),
  HO_OH_81 ("Ho-oh", "81", Rarity.RARE, [BASIC, POKEMON, _COLORLESS_]),
  LUGIA_82 ("Lugia", "82", Rarity.RARE, [BASIC, POKEMON, _COLORLESS_]),
  ARTICUNO_83 ("Articuno", "83", Rarity.RARE, [BASIC, POKEMON, _WATER_]),
  MOLTRES_84 ("Moltres", "84", Rarity.RARE, [BASIC, POKEMON, _FIRE_]),
  ZAPDOS_85 ("Zapdos", "85", Rarity.RARE, [BASIC, POKEMON, _LIGHTNING_]),
  ARTICUNO_EX_86 ("Articuno", "86", Rarity.ULTRARARE, [BASIC, POKEMON, _WATER_]),
  MOLTRES_EX_87 ("Moltres", "87", Rarity.ULTRARARE, [BASIC, POKEMON, _FIRE_]),
  ZAPDOS_EX_88 ("Zapdos", "88", Rarity.ULTRARARE, [BASIC, POKEMON, _LIGHTNING_]),
```

2020-10-03 17:44 UTC, flagrama commented
Ah, I would request that you create new PRs for different files. Otherwise this one gets even harder and harder to review.

2020-10-03 17:57 UTC, flagrama commented on src/tcgwars/logic/impl/pokemod/PokemodFossil.groovy
> +          }
This is a pokeBody in Pokémod, not a Pokémon Power. You should also update the "text" value where appropriate to match what is on the Pokémod card. Keeping the text accurate helps with reviewing the changes to ensure they are accurate to the text on the card without having to load the carddb in the browser.

2020-10-03 18:00 UTC, flagrama commented on src/tcgwars/logic/impl/pokemod/PokemodFossil.groovy
> +            }
```suggestion
              before PLAY_EVOLUTION, {
                if(!self.specialConditions && self.cards.filterByType(POKEMON_TOOL)){
                  wcu "Prehistoric Power prevents you from playing Evolution cards!"
                  prevent()
                }
              }
            }
```
You need to check the tool is attached inside of the `before`. Checking it outside will prevent the delayed effect from ever being registered if you don't have a tool attached when Aerodactly comes into play, even if you attach it later.

2020-11-07 05:26 UTC, flagrama commented on src/tcgwars/logic/impl/pokemod/PokemodFossil.groovy
> +              extraEnergyDamage(2,hp(10),W,thisMove)nergy attached to Lapras but not used to pay for this attack’s Energy cost. You can’t add more than 20 damage in this way
This needs fixed since it'll cause an error.

2021-03-16 20:38 UTC, flagrama commented
GitHub doesn't seem to be showing my rebase and fix build force push in it's log here, but the files seem to have been updated. If everything seems alright after this comment, I'm just going to merge this so this can actually be tested and bugs fixed. It's way to large to review easily.

2021-03-16 20:39 UTC, merged