Add method to only get the live expansions
axpendix/tcgone-engine-contrib pull request #974
Opened 2020-10-18 03:09 UTC by flagrama

This gives us the opportunity to add sets to the server without making them visible in the deck editor and play server card database.

Just add a new item to the list of dev-only IDs in the private method and the public one should return the list of all other expansions.

2020-10-21 18:35 UTC, axpendix reviewed
-

2020-10-21 18:41 UTC, axpendix requested changes
Hey, I think this could be better handled with an auto-logic like this: run through all active formats for each `GameType`, then get `Collection`s for each `GameFormat`, put them in a set, the remaining `Collections` are dev-only.

2020-10-21 20:42 UTC, flagrama commented
That certainly sounds like a better idea. I suppose it would also let us set up formats for Dev for testing if any rule changes occur which could be nice. Would the code still be here in Collection, or do you think there is a more proper place for it?

2020-10-21 21:30 UTC, axpendix commented
> That certainly sounds like a better idea. I suppose it would also let us set up formats for Dev for testing if any rule changes occur which could be nice. Would the code still be here in Collection, or do you think there is a more proper place for it?

👍 `Collection` should be a fine place for this

2020-10-23 09:36 UTC, axpendix approved these changes

2020-10-23 14:13 UTC, merged